# Generated by Django 5.2.6 on 2025-09-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('surname', models.CharField(max_length=100, verbose_name='Nom')),
                ('biography', models.TextField(max_length=300, verbose_name='Biographie')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('duration', models.DurationField(verbose_name='Durée')),
                ('genre', models.CharField(max_length=100, verbose_name='Genre')),
            ],
        ),
    ]
