# Generated by Django 5.2.6 on 2025-09-12 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('biography', models.TextField(max_length=300, verbose_name='Biographie')),
            ],
            options={
                'verbose_name': 'acteur',
                'verbose_name_plural': 'acteurs',
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('places', models.PositiveIntegerField(verbose_name='Places')),
                ('reservation_date', models.DateTimeField(auto_now_add=True, verbose_name='Date réservation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'réservation',
                'verbose_name_plural': 'réservations',
                'ordering': ('reservation_date',),
            },
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(verbose_name='Heure')),
                ('hall', models.CharField(max_length=50, verbose_name='Salle')),
            ],
            options={
                'verbose_name': 'séance',
                'verbose_name_plural': 'séances',
                'ordering': ('date', 'time'),
            },
        ),
        migrations.DeleteModel(
            name='Acteur',
        ),
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ('title',), 'verbose_name': 'film', 'verbose_name_plural': 'films'},
        ),
        migrations.AddField(
            model_name='film',
            name='poster',
            field=models.ImageField(default='img/default.png', upload_to='img/', verbose_name='Affiche'),
        ),
        migrations.AddField(
            model_name='film',
            name='actors',
            field=models.ManyToManyField(related_name='films', to='demo_app.actor', verbose_name='Acteurs'),
        ),
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo_app.genre', verbose_name='Genre'),
        ),
        migrations.AddField(
            model_name='seance',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='demo_app.film', verbose_name='Films'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='demo_app.seance', verbose_name='Seance'),
        ),
    ]
