# Generated by Django 5.2.6 on 2025-10-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='biography_en',
            field=models.TextField(max_length=300, null=True, verbose_name='Biographie'),
        ),
        migrations.AddField(
            model_name='actor',
            name='biography_fr',
            field=models.TextField(max_length=300, null=True, verbose_name='Biographie'),
        ),
        migrations.AddField(
            model_name='actor',
            name='first_name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Prénom'),
        ),
        migrations.AddField(
            model_name='actor',
            name='first_name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Prénom'),
        ),
        migrations.AddField(
            model_name='actor',
            name='last_name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='actor',
            name='last_name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='film',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='film',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='film',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='film',
            name='title_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='genre',
            name='name_en',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Genre'),
        ),
        migrations.AddField(
            model_name='genre',
            name='name_fr',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Genre'),
        ),
        migrations.AddField(
            model_name='hall',
            name='name_en',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Salle'),
        ),
        migrations.AddField(
            model_name='hall',
            name='name_fr',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Salle'),
        ),
    ]
