# Generated by Django 5.2.6 on 2025-10-03 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0002_actor_biography_en_actor_biography_fr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='first_name_en',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='first_name_fr',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='last_name_en',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='last_name_fr',
        ),
    ]
